/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.jpanelimage;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author a22dianart
 */
public class ImaxeFondoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImaxeFondoPanel
     */
    public ImaxeFondoPanel() {
        initComponents();
    }

    public ImaxeFondo getSelectedValue() {
        File file = new File(imaxeTxt.getText());
// Engádese o f para converter o enteiro a float
        Float opacidade = opacidadeSlider.getValue() / 100f;
        return new ImaxeFondo(file, opacidade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imaxeLbl = new javax.swing.JLabel();
        imaxeTxt = new javax.swing.JTextField();
        imaxeBtn = new javax.swing.JButton();
        opacidadeLbl = new javax.swing.JLabel();
        opacidadeSlider = new javax.swing.JSlider();

        imaxeLbl.setText("Imaxe:");

        imaxeTxt.setEditable(false);
        imaxeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imaxeTxtActionPerformed(evt);
            }
        });

        imaxeBtn.setText("...");
        imaxeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imaxeBtnActionPerformed(evt);
            }
        });

        opacidadeLbl.setText("Opacidade:");

        opacidadeSlider.setValue(50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opacidadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imaxeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imaxeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(opacidadeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(imaxeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imaxeLbl)
                    .addComponent(imaxeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imaxeBtn))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opacidadeLbl)
                    .addComponent(opacidadeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imaxeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imaxeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imaxeTxtActionPerformed

    private void imaxeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imaxeBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
// Se se selecciona un arquivo e se pulsa aceptar
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            imaxeTxt.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_imaxeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imaxeBtn;
    private javax.swing.JLabel imaxeLbl;
    private javax.swing.JTextField imaxeTxt;
    private javax.swing.JLabel opacidadeLbl;
    private javax.swing.JSlider opacidadeSlider;
    // End of variables declaration//GEN-END:variables
}
