/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.exercicio3;

import java.awt.Color;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.ColorChooserComponentFactory;

/**
 *
 * @author a22dianart
 */
public class CorPanel extends javax.swing.JPanel {

    /**
     * Creates new form CorPanel
     */
    public CorPanel() {
        initComponents();
    }

    public Cor getSelectedValue() {
        String textoColor = textoField.getText();
        String fondoColor = fondoField.getText();

        int textoColorRed;
        int textoColorGreen;
        int textoColorBlue;

        int fondoColorRed;
        int fondoColorGreen;
        int fondoColorBlue;
        //---------------------------------------------------------------------------------------------

        if (textoColor.length() != 0) {
            int textoColorFirstIndex = textoColor.indexOf(",");
            int textoColorMediumIndex = textoColor.lastIndexOf(",");
            int textoColorLastIndex = textoColor.lastIndexOf("]");

            textoColorRed = Integer.parseInt(textoColor.substring(1, textoColorFirstIndex));
            textoColorGreen = Integer.parseInt(textoColor.substring(textoColorFirstIndex + 1, textoColorMediumIndex));
            textoColorBlue = Integer.parseInt(textoColor.substring(textoColorMediumIndex + 1, textoColorLastIndex));

        } else {
            textoColorRed = 0;
            textoColorGreen = 0;
            textoColorBlue = 0;

        }

        //--------------------------------------------------------------------------------------------
        if (fondoColor.length() != 0) {
            int fondoColorFirstIndex = fondoColor.indexOf(",");
            int fondoColorMediumIndex = fondoColor.lastIndexOf(",");
            int fondoColorLastIndex = fondoColor.lastIndexOf("]");

            fondoColorRed = Integer.parseInt(fondoColor.substring(1, fondoColorFirstIndex));
            fondoColorGreen = Integer.parseInt(fondoColor.substring(fondoColorFirstIndex + 1, fondoColorMediumIndex));
            fondoColorBlue = Integer.parseInt(fondoColor.substring(fondoColorMediumIndex + 1, fondoColorLastIndex));

        } else {
            fondoColorRed = 255;
            fondoColorGreen = 255;
            fondoColorBlue = 255;
        }

        //-----------------------------------------------------------------------------------------
        Color colorTexto = new Color(textoColorRed, textoColorGreen, textoColorBlue);
        Color colorFondo = new Color(fondoColorRed, fondoColorGreen, fondoColorBlue);
        return new Cor(colorFondo, colorTexto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoLbl = new javax.swing.JLabel();
        fondoLbl = new javax.swing.JLabel();
        textoField = new javax.swing.JTextField();
        fondoField = new javax.swing.JTextField();
        selectTextBtn = new javax.swing.JButton();
        selectFondoBtn = new javax.swing.JButton();

        textoLbl.setText("Cor fondo:");

        fondoLbl.setText("Cor texto:");

        textoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFieldActionPerformed(evt);
            }
        });

        fondoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fondoFieldActionPerformed(evt);
            }
        });

        selectTextBtn.setText("...");
        selectTextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTextBtnActionPerformed(evt);
            }
        });

        selectFondoBtn.setText("...");
        selectFondoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFondoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fondoLbl)
                    .addComponent(textoLbl))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(fondoField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectTextBtn)
                    .addComponent(selectFondoBtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fondoLbl)
                    .addComponent(textoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTextBtn))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLbl)
                    .addComponent(fondoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFondoBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFieldActionPerformed

    private void selectTextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTextBtnActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        int resultado = JOptionPane.showConfirmDialog(null, colorChooser, "Selecciona un color", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (resultado == JOptionPane.OK_OPTION) {
            Color color = colorChooser.getColor();
            StringBuilder sb = new StringBuilder();
            sb.append("[");
            sb.append(color.getRed());
            sb.append(",");
            sb.append(color.getGreen());
            sb.append(",");
            sb.append(color.getBlue());
            sb.append("]");
            textoField.setText(sb.toString());
        }
    }//GEN-LAST:event_selectTextBtnActionPerformed

    private void selectFondoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFondoBtnActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        int resultado = JOptionPane.showConfirmDialog(null, colorChooser, "Selecciona un color", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (resultado == JOptionPane.OK_OPTION) {
            Color color = colorChooser.getColor();
            StringBuilder sb = new StringBuilder();
            sb.append("[");
            sb.append(color.getRed());
            sb.append(",");
            sb.append(color.getGreen());
            sb.append(",");
            sb.append(color.getBlue());
            sb.append("]");
            fondoField.setText(sb.toString());
        }
    }//GEN-LAST:event_selectFondoBtnActionPerformed

    private void fondoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fondoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fondoFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fondoField;
    private javax.swing.JLabel fondoLbl;
    private javax.swing.JButton selectFondoBtn;
    private javax.swing.JButton selectTextBtn;
    private javax.swing.JTextField textoField;
    private javax.swing.JLabel textoLbl;
    // End of variables declaration//GEN-END:variables
}
